services:
  sql:
    build:
      context: .
      dockerfile: sql.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    build:
      context: .
      dockerfile: phpmyadmin.Dockerfile
    container_name: phpmyadmin
    restart: always
    ports:
      - "9000:80"
    environment:
      TZ: America/Sao_Paulo
      PMA_HOST: sql
      PMA_PORT: 3306
    volumes:
      - ./docker/:/etc/apache2/sites-available/
    networks:
      - default

networks:
  default: